tryDjango/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name = 'index'), 
    path('<str:name>', views.greet, name='greet'),
    path('michael', views.michael, name = 'index'), 
    
]

tryDjango/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index')
]

tryDjango/tasks/urls.py
from django.urls import path 

from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('add', views.add, name = 'add')
]

tryDjango/tryDjango/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('tasks/', include('tasks.urls')),
    path('newyear/', include('newyear.urls')),
]

tryDjango/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.test import TestCase

# Create your views here.
def index(request):
    return render(request, 'hello/index.html')

def michael(request):
    return HttpResponse('Hello, Michael')

def greet(request, name):
    return render(request, 'hello/greet.html', {
        "name": name.capitalize()
    })

tryDjango/newyear/views.py
import datetime
from django.shortcuts import render


# Create your views here.

def index(request):
    now = datetime.datetime.now()
    return render(request, 'newyear/index.html', {
        # 'newyear': now.month == 1 and now.day ==1,
        'newyear': True,
    })
    

tryDjango/tasks/views.py
import tasks
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


class newTaskForm(forms.Form):
    task = forms.CharField(label = 'new task')
    # priority = forms.IntegerField(label = 'priority', min_value=1, max_value=5)

# Create your views here.
def index(request):
    if 'tasks' not in request.session:
        request.session['tasks'] = []
        
    return render(request, 'tasks/index.html', {
        'tasks': request.session['tasks']
    })
    
def add(request):
    if request.method == 'POST':
        form = newTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data['task']
            request.session['tasks'] += [task]
            return HttpResponseRedirect(reverse('tasks:index'))
        else:
            return render(request, 'tasks/add.html', {
                'form': form
            })
        
    return render(request, 'tasks/add.html', {
        'form': newTaskForm()
    })

tryDjango/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello, {{ name }}!</h1>
</body>
</html>

tryDjango/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello, world!</h1>
</body>
</html>

tryDjango/newyear/templates/newyear/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Is it newyears?</title>
</head>
<body>
    {% if newyear %}
        <h1>yes</h1>
    {% else %}
        <h1>no</h1>
    {% endif %}
</body>
</html>

tryDjango/tasks/templates/tasks/add.html
{% extends 'tasks/layout.html' %}

{% block body %}
    <h1>Add task</h1>
    <form action = '{% url 'tasks:add' %}' method = 'post'>
        {% csrf_token %}
        {{ form }}
        <input type="submit"></input>
    </form>
    <a href="{% url 'tasks:index' %}">view tasks</a>
{% endblock %}

tryDjango/tasks/templates/tasks/index.html
{% extends 'tasks/layout.html' %}

{% block body %}
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
            <li>No tasks.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">add a new task</a>
{% endblock %}

tryDjango/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>